---
- name: "MySQL | install mysql packages"
  apt: pkg={{ item }} state=installed
  become: yes
  become_method: sudo
  with_items:
   - mysql-client-5.6
   - mysql-server-5.6
   - mysql-common-5.6
   - python-mysqldb

- name: "MySQL | create MySQL configuration file"
  template:
    src=my.cnf.j2
    dest=/etc/mysql/my.cnf
    backup=yes
    owner=root
    group=root
    mode=0644
  become: yes
  become_method: sudo

- name: "MySQL | restart mysql"
  service: name=mysql state=restarted
  become: yes
  become_method: sudo

- name: "Having default root user present for all hosts (automation purposes, your connections must be protected by a firewall)"
  mysql_user: login_user=root
              login_password=''
              name={{ dbuser }}
              password={{ dbpass }}
              priv=*.*:ALL,GRANT
              host=%
              state=present
  ignore_errors: True

# MySQL database setup, this does the equivalent of mysql_secure_installation.
#- name: "MySQL | Set the root password."
#  mysql_user: name=root password={{ mysql_root_password }} host=localhost
#  become: yes
#  become_method: sudo
#  ignore_errors: True

- name: "Create {{ dbname }} database"
  mysql_db: name={{ dbname }} encoding=utf8 state=present login_user=root login_password=''
  ignore_errors: True

- name: MySQL | Remove the MySQL test database
  mysql_db: db=test state=absent login_user=root login_password=''

- name: MySQL | restart mysql
  service: name=mysql state=restarted
  become: yes
  become_method: sudo
