- name: Install python
  apt: name=python update_cache=yes

- name: Install python DEV
  apt: name=python-dev update_cache=yes

- name: Install python PIP
  apt: name=python-pip update_cache=yes

- name: Install Jinja2
  pip: name=jinja2