---
- name: Nginx | install nginx
  apt: pkg=nginx state=installed
  become: true
  become_user: "{{ user }}"

- name: Nginx | nginx settings
  template: src=nginx.conf.j2
            dest=/etc/nginx/nginx.conf
            backup=yes
  become: true
  become_user: "{{ user }}"
  notify:
    - restart nginx

- name: Nginx | disable default server block
  file: path=/etc/nginx/sites-enabled/default
        state=absent
  become: true
  become_user: "{{ user }}"
  notify:
    - restart nginx

#- name: Nginx | set default login directory
#  lineinfile: dest={{ home_dir }}/.bashrc state=present line='cd {{ sites_dir }}'

- name: Nginx | restart nginx
  service: name=nginx state=restarted
  become: true
  become_user: "{{ user }}"
