---
- name: Install apache2
  apt: name=apache2 state=present

- name: Remove default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache
