---
galaxy_info:
  author: Kisphp
  description: "An Ansible role for setting up Vsftpd Ubuntu LTS 12.04 (precise), or 14.04 (trusty)"
  company:
  license: MIT
  min_ansible_version: 1.7
  platforms:
  - name: Ubuntu
    versions:
      - precise
      - trusty
  categories:
    - system
dependencies: []
