---
- name: Kisphp dotfiles
  shell: curl https://raw.githubusercontent.com/kisphp/dotfiles/master/install.sh | bash -
  become: true
  become_user: "{{ user }}"
  args:
    chdir: /home/{{ user }}
    executable: /bin/bash
