---
# Configuration file
# Change settings here to control how your box is set up.

user: vagrant

document_root: /home/{{ user }}/server
server_name: ansible.local

server_timezone: Europe/Berlin

# NodeJS
# Pin-Priority of NodeSource repository
nodejs_nodesource_pin_priority: 500
nodejs_version: "6.x"

# php package
php:
  package: php5
  modules:
    - cli
  composer:
    present: True
    auth: []

# php.ini settings
php_memory_limit: 512M
php_max_execution_time: 60
php_post_max_size: 100M
php_upload_max_filesize: 100M
php_display_errors: On
php_display_startup_errors: On
php_html_errors: On

php_allow_url_fopen: Off
php_error_reporting: E_ALL & ~E_DEPRECATED & ~E_STRICT

# php xdebug settings
php_xdebug_idekey: PHPSTORM
php_xdebug_remote_enable: 1
php_xdebug_remote_autostart: 1
php_xdebug_profiler_enable: 1
php_xdebug_remote_connect_back: 1

# MySQL Settings
mysql_port: 3306
mysql_root_password: root
server_hostname: localhost
dbuser: developer
dbpass: develop123
dbname: development

# MySQL my.cnf settings
mysql_max_allowed_packet: 128M
mysql_character_set_server: utf8
mysql_collation_server: utf8_general_ci

# Local hosts file location
# Default location on *nix hosts is '/etc/hosts'
hosts_file_location: "/etc/hosts"

# Set the level of verbosity that Ansible will use
# This can be one of "", "v", "vv", "vvv", or "vvvv"
ansible_verbosity: ""
