  - hosts: all
    connection: local
    become: yes
    become_method: sudo
    vars_files:
      - settings.yml
    pre_tasks:
      - name: update apt cache
        apt: update_cache=yes
    roles:
      - general
      - frontend
      - webserver
      - database
